import { type NextPage } from "next"
import Head from "next/head"
import { signIn, useSession } from "next-auth/react"
import Image from "next/image"
import { mainGradient } from "../utils/gradient"
import Link from "next/link"
import ProfilePicture from "../components/ProfilePicture"

const Home: NextPage = () => {
  const session = useSession()

  return (
    <>
      <Head>
        <title>PlanITLY</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center p-8">
        <h1
          className={
            "bg-clip-text text-center text-7xl font-extrabold md:text-9xl "
          }
        >
          PlanITLY
        </h1>
        <div className="my-auto flex flex-col gap-4 items-center">
          <Image
            src="/assets/images/pages/index/illustration.svg"
            width={500}
            height={500}
            alt="illustration"
          />
          <p
            className={
              "bg-clip-text text-2xl font-bold text-transparent md:w-2/3 md:text-7xl " +
              mainGradient
            }
          >
            Let&apos;s upgrade the way you plan things in your life
          </p>
          <p className="text-md font-bold">
            Are you looking for a way to manage all tasks, meetings, events,
            trips in one place easier than ever? Well, you found the way now!
          </p>
        </div>
        <div className="flex w-full flex-col gap-2">
          <button
            className={
              "mt-auto w-full rounded-full border border-black py-4 text-2xl font-bold drop-shadow-lg md:w-fit md:px-16 md:text-3xl " +
              (session.status !== "authenticated"
                ? "text-white "
                : "bg-clip-text text-transparent ") +
              mainGradient
            }
            onClick={() => void signIn()}
          >
            {session.status === "authenticated"
              ? "CHANGE ACCOUNT"
              : "LOGIN WITH GOOGLE"}
          </button>
          <Link
            className={
              "mt-auto w-full rounded-full py-4 text-center text-2xl font-bold text-white drop-shadow-lg md:w-fit md:px-16 md:text-3xl " +
              (session.status !== "authenticated"
                ? "pointer-events-none opacity-75 "
                : "") +
              mainGradient
            }
            href="/dashboard"
          >
            <div className="flex flex-col gap-2">
              <p>GO TO APP</p>
              {session.data && (
                <div className="flex items-center gap-2 self-center text-sm">
                  <ProfilePicture
                    src={session.data.user.image as string}
                    size={28}
                  />
                  <p>
                    {` ${session.data.user.firstName} ${session.data.user.lastName}`}
                  </p>
                </div>
              )}
            </div>
          </Link>
        </div>
      </main>
    </>
  )
}

export default Home
