import { type NextPage } from "next"
import { signIn, useSession } from "next-auth/react"
import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import { useRouter } from "next/router"
import React, { useEffect } from "react"

const Home: NextPage = () => {
  const session = useSession()
  const router = useRouter()

  useEffect(() => {
    if (session.status === "authenticated") {
      void router.push("/dashboard/calendar")
    }
  }, [session.status])

  return (
    <>
      <Head>
        <title>PlanITLY - Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center gap-8 p-8">
        <div className="flex flex-col items-center gap-2">
          <Image
            src="/assets/images/pages/index/illustration.svg"
            width={500}
            height={500}
            alt="illustration"
          />
          <h1 className="w-full text-left text-2xl font-bold mb-2">
            Login Details
          </h1>
          <InputField label="Username, email, phone number" />
          <InputField label="Password" />
          <Link href="/" className="w-full text-right font-bold text-gray-500">
            Forgot Password?
          </Link>
        </div>
        <div className="flex w-full flex-col gap-8">
          <button className="h-16 w-full rounded bg-teal-600 text-center text-2xl font-bold text-white">
            LOGIN
          </button>
          <div className="flex items-center gap-4">
            <span className="h-1 flex-1 bg-gradient-to-l from-teal-600" />
            <p className="gray-400 text-center text-xs font-bold text-gray-500">
              Or Sign up With
            </p>
            <span className="h-1 flex-1 bg-gradient-to-r from-teal-600" />
          </div>
          <div className="flex items-center justify-center gap-8">
            <button
              className="rounded-full bg-gray-200 p-4"
              onClick={() => void signIn()}
            >
              <Image
                alt="google logo"
                width={32}
                height={32}
                src="https://companieslogo.com/img/orig/GOOG-0ed88f7c.png?t=1633218227"
              />
            </button>
            <button className="rounded-full bg-gray-200 p-4">
              <Image
                alt="facebook logo"
                width={32}
                height={32}
                src="https://www.facebook.com/images/fb_icon_325x325.png"
              />
            </button>
            <button className="flex h-16 w-16 rounded-full bg-gray-200">
              <Image
                className="m-auto h-8 w-auto"
                alt="apple logo"
                width={32}
                height={32}
                src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/488px-Apple_logo_black.svg.png?20220821121934"
              />
            </button>
          </div>
        </div>
        <div className="absolute -bottom-0">
          <Image
            className=""
            alt="bottom illustration"
            src="/assets/images/pages/index/bottom-illustration.svg"
            width={768}
            height={100}
          />
        </div>
      </main>
    </>
  )
}

const InputField: React.FC<{
  label: string
}> = ({ label }) => {
  return (
    <div className="relative w-full">
      <label className="absolute top-2 left-4 text-xs font-bold text-gray-400">
        {label}
      </label>
      <input className="w-full rounded border border-gray-400 px-4 pb-2 pt-6" />
    </div>
  )
}

export default Home
