import { type NextPage } from "next"
import Head from "next/head"
import { signIn } from "next-auth/react"
import Image from "next/image"
import { mainGradient } from "../utils/gradient"

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>PlanITLY</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center p-8">
        <h1
          className={
            "bg-clip-text text-center text-7xl font-extrabold md:text-9xl "
          }
        >
          PlanITLY
        </h1>
        <div className="my-auto flex flex-col gap-4">
          <Image
            src="/assets/images/pages/index/illustration.svg"
            width={500}
            height={500}
            alt="illustration"
          />
          <p
            className={
              "bg-clip-text text-2xl font-bold text-transparent md:w-2/3 md:text-7xl " +
              mainGradient
            }
          >
            Let&apos;s upgrade the way you plan things in your life
          </p>
          <p className="text-md font-bold">
            Are you looking for a way to manage all tasks, meetings, events,
            trips in one place easier than ever? Well, you found the way now!
          </p>
        </div>
        <button
          className={
            "mt-auto w-full rounded-full py-4 text-2xl font-bold text-white drop-shadow-lg md:w-fit md:px-16 md:text-3xl " +
            mainGradient
          }
          onClick={() => void signIn()}
        >
          LOGIN
        </button>
      </main>
    </>
  )
}

export default Home
