name: prod workflow

on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  docker-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build --build-arg NEXT_PUBLIC_REALTIME_URL=http://realtime:8080 . -t octavianregatun/planitly:dev

      - name: Docker push
        run: docker push octavianregatun/planitly:dev